name: CI - Frontend Web 
 
on: 
  push: 
    branches: [main, develop] 
    paths: 
      - "apps/web/**" 
  pull_request: 
    branches: [main] 
    paths: 
      - "apps/web/**" 
 
jobs: 
  lint: 
    name: Lint et Format 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v4 
      - uses: actions/setup-node@v4 
        with: 
          node-version: 20 
      - run: cd apps/web && npm install 
      - run: cd apps/web && npx eslint src/ 
      - run: cd apps/web && npx prettier --check src/ 
